name: Pull Request Close
on:
  pull_request:
    branches:
        - main
    types:
        - closed

jobs:
  pull-request-close:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Pull Request Closed"