name: Pull Request Close
on:
  pull_request:
    branches:
      - main
    types:
        - closed
  delete:

jobs:
  pull-request-close:
    runs-on: ubuntu-latest
    steps:
      - name: Output context
        if: github.event_name == 'pull_request'
        run: |
            echo "The event name is ${{ github.event_name }} and the action is ${{ github.event.action }}" 
            echo "The pull request number is ${{ github.event.pull_request.number }}"
            echo "The pull request title is ${{ github.event.pull_request.title }}"
            echo "The pull request body is ${{ github.event.pull_request.body }}"
            echo "The pull request state is ${{ github.event.pull_request.state }}"
            echo "The pull request merged is ${{ github.event.pull_request.merged }}"
            echo "The pull request merged by is ${{ github.event.pull_request.merged_by }}"

      - name: Output branch deletion context
        if: github.event.ref_type == 'branch'
        run: |
            echo "The ref is ${{ github.event.ref }}"
            echo "The ref_type is ${{ github.event.ref_type }}"
            echo "The ref is deleted ${{ github.event.deleted }}"
            echo "The ref is created ${{ github.event.created }}"
            echo "The ref is updated ${{ github.event.updated }}"
            echo "The ref is ref_type ${{ github.event.ref_type }}"
            echo "The pull request is ${{ github.event.pull_request }}""